### ISSUE TITLE
Prevent transitive dependencies error using dynamic library

### ISSUE THREAD

**Issue by mrcararia** [microsoft/appcenter-sdk-apple#1227]
Hello,

I would like to migrate from HockeyApp to AppCenter.
I have developed my own cocoapods library using 'HockeySDK-Source' as transitive dependency of my framework. Trying to migrate to AppCenter, cocoapods install end with error:
"target has transitive dependencies that include static binaries:"

Is possible to deploy a dynamic version of this cocoapod?
This is necessary to create a private pod using frameworks, needed when there are swift classes in Xcode project.

Thanks.

**Comment by achocron** [comment]
Unfortunately, we have no plans to release a dynamic framework version of the App Center SDK.

However, based on [a thread](https://github.com/CocoaPods/CocoaPods/issues/3267), some users had success by adding 
```
pre_install do |installer|
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```
to their Podfile. I am not sure if it will work for you, but it might be worth a try.

**Comment by clpolet** [comment]
@mrcararia did you get it working with @achocron suggestions?

**Comment by mrcararia** [comment]
@clpolet No, this not solve my problem. The issue occurs when I execute `pod lib lint` to test if the podspec and the resources to produce a private framework are ok. Lint operation failed with error:

`[!] The 'Pods-<MyFrameworkName>' target has transitive dependencies that include static binaries: (<projectDir>/Pods/AppCenter/AppCenter-SDK-Apple/iOS/AppCenterAnalytics.framework, <projectDir>/Pods/AppCenter/AppCenter-SDK-Apple/iOS/AppCenter.framework, and <projectDir>/Pods/AppCenter/AppCenter-SDK-Apple/iOS/AppCenterCrashes.framework) `

**Comment by clpolet** [comment]
Sorry for the late reply. HockeyApp and AppCenter are both static fat framework, they both have a crash reporter (another static fat framework) as dependency. The difference is the possibility to build HockeyApp from source and that's what you were using. Basically AppCenter doesn't have an AppCenter-Source pod to pull the source instead of the binaries into your project. This is not in our [road-map for the transition to AppCenter](https://hockeyapp.net/transition/) but we'll still keep the feature request open in case it find its way into our road map.

**Comment by mrcararia** [comment]
Any updates on that?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
