### ISSUE TITLE
The bundle format of the provided Mac frameworks is invalid

### ISSUE THREAD

**Issue by depth42** [Microsoft/AppCenter-SDK-Apple#1249]
The bundle structures of the following Mac frameworks are invalid:

AppCenter.framework
AppCenterAnalytics.framework
AppCenterCrashes.framework
AppCenterPush.framework

It looks like these Mac frameworks use the iOS framework bundle structure which is invalid on the Mac. See the following documentation for details: https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW28

When you try to embed the frameworks into a Mac app, this leads to the following code-signing error:

Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug/MyApp.app/Contents/Frameworks/AppCenter.framework/Versions/A: bundle format unrecognized, invalid, or unsuitable
Command CodeSign failed with a nonzero exit code

**Comment by ElektrojungeMS** [comment]
Hey @depth42,

Thanks for getting in touch and a big "hello" to Frankfurt! =)

You are right that the SDK binary is not packaged following the macOS framework convention. The reason is that the App Center SDK for Mac is actually not a conventional framework but a static library that is packaged as a "fake fat framework". Can you remove the references to the App Center SDK in your project and integrate it as a static framework? Make sure you are not embedding the binaries, and don't include them in the "copy bundle resources" build phase; just link them. 

<img width="1115" alt="screen shot 2018-12-04 at 1 57 20 pm" src="https://user-images.githubusercontent.com/10164200/49475665-a77a4f80-f7cc-11e8-9cf8-6ee255def3fe.png">
<img width="949" alt="screen shot 2018-12-04 at 1 57 33 pm" src="https://user-images.githubusercontent.com/10164200/49475666-a77a4f80-f7cc-11e8-8d1e-5f2b16f39d88.png">

If this doesn't help, please let me know how you integrate the SDK (binary integration or Cocoapods), which version of the SDK you are using as well as your Xcode version.

Also:
any feedback is very welcome!

Thanks for trying App Center!

Cheers!
Benjamin

**Comment by depth42** [comment]
Hi Benjamin,

as you advised, I could solve the problem by simply NOT embedding the (static) frameworks.
Thank you for your help.

Cheers

Frank

**Comment by lov** [comment]
Hey there,

please, at least mention this in the Getting Started docs... spent at least 1 hour figuring out what is going wrong until I accidentally found this ticket...

Thank you!

**Comment by annakocheshkova** [comment]
@Iov good point. We will.

**Comment by annakocheshkova** [comment]
@lov Updated the docs.
