### ISSUE TITLE
Add support for iOS 8

### ISSUE THREAD

**Issue by ForkBug** [microsoft/appcenter-sdk-apple#1257]
As a third party lib, IOS 9 is a really high version

**Comment by ElektrojungeMS** [comment]
Hey @ForkBug,

Personally, I don't agree that iOS 9 is a really high version. 
For the App Center SDK, setting iOS 9 as a minimum iOS version was a decision that we made based on iOS version distribution numbers from Apple and other sources. Supporting very old iOS versions (iOS 8 was released in 2014) comes at a high cost for code maintenance, testing and support.

Some numbers you might want to look at:
* [Apple's own iOS version distribution numbers](https://developer.apple.com/support/app-store/) don't list iOS 8, they list versions lower than iOS 11 at 9%.
* [Apteligent](https://data.apteligent.com/ios/) lists iOS 8 usage at 2.15%.
* [Mixpanel](https://mixpanel.com/trends/#report/ios_12) lists versions lower than iOS 11 at 5.62%.

What's the number of iOS 8 usage for your app?

Best,
Benjamin

**Comment by ElektrojungeMS** [comment]
I agree that being inclusive of users is important and I applaud that you are taking support for lower iOS versions very seriously. Be assured, we take support for old iOS versions very seriously, too.

That said, I want to provide some more data points to you behind our rationale: the last device to get the update to iOS 9 was the iPhone 4s, a device that was released in 2011. So by dropping iOS 8 support, we are dropping support for devices that are older than 7 years, a number that on other OS's, e.g. Android, is pretty much unheard of.

Supporting crash reporting, analytics, in-app updates and push notifications across 5 major iOS versions, 3 Xcode versions (while new versions of iOS are typically supported, building apps for older iOS versions gets removed eventually) is very complex from an development as well as form a testing perspective (you really don't want to see our test matrix of iPhones/iPads, iOS versions and Xcode versions). We decided to drop iOS 8 because we cannot justify the investment supporting it required from our side. Honestly, if you look at the iOS version usage today, it's hard to even justify supporting iOS 9 but like I said, we care a lot about inclusivity and thus support for old OS versions, so continue to support iOS 9.

That all said, you did not answer my question:
What numbers of iOS 8 usage are you seeing? Are you seeing a significant usage of iOS 8 and devices older than the iPhone 4s in you audience? I'm serious with my questions, you are the first person to ask for iOS 8 support since we first dropped the support (counting AppCenter and HockeyApp here) and we would love to know more facts here.

Best,
Benjamin

**Comment by ElektrojungeMS** [comment]
Hey @ForkBug ,

I get what you're saying but I don't want to get into an argument where I compare software engineering in the 90s vs. today, or compare serverside vs app development, so let's leave it at that. ;) 

Thanks for sharing the iOS 8 usage number with us. I have renamed the issue to reflect what you are asking and tagged it as a feature request. That said, you are the first person to ask for iOS 8 support that we are aware of. We do not plan to add support for iOS 8 at this time but will revisit that decision if we get more asks for it.

Now, about your questions around App Center Test: Please check our documentation for [App Center Test](https://docs.microsoft.com/en-us/appcenter/test-cloud/) and get in touch through our Intercom (the blue button at the bottom right corner on the App Center portal). The issues here on GitHub are intended for reporting problems related to the SDKs and not a general support platform for all of App Center (that's our Intercom which I mention in the last sentence).

Thanks for your feedback and for using App Center!

Benjamin

**Comment by katsumoto** [comment]
Hi guys, want to add some other perspective, why iOS 8 is important.

We are an logistics network,we have around 1500 locations and growing, which we equip with iPhones and our inHouse App(Apple Enterprise/InHouse program). 

Due to the cost as we started the company, we bought used iPhone4s.
This is now a constraint, because we have to support iOS8!!! It would be to expensive to buy around 1200new phones. Although from the tech perspective of course we would like to.

We are using hockey for distributing our inouse app and crash reporting.

I imagine, we are not the only inhouse/Entperise app, which have this kind of constraints.
And I suspect a lot of B2B Inhouse Apps which are using Hockey, did not take a look into the migration yet...so questions is, what will be the demand for iOS8 when the migration will be forced next nov.



@ElektrojungeMS I home this adds some perspective. 
Cheers

**Comment by katsumoto** [comment]
@ElektrojungeMS 
we have currently 3.8.6.
Sorry my bad, you are right. We have currently some iPhone4 (NO S) in our network.
For all our new locations we are using iPhone4s and 5s - But this is rather a slow step not a "hard" quick migration.

Best Michael

**Comment by MatkovIvan** [comment]
@katsumoto but the final supported OS for iPhone 4 is iOS 7, so support of iOS 8 won't change anything in this case

**Comment by katsumoto** [comment]
@MatkovIvan 
I had somehow iOS8 in my head for the iPhone4...it is XCode8 we have to use to build for deployment target iOS7...got it mixed up...

So I assume iOS7 support is little bit to much to hope for :/

**Comment by jaelim-ms** [comment]
@katsumoto Do you still need iOS 8 support?
I'm sorry to say that we are not going to support iOS 8. All devices that can be running in iOS 8 could be upgraded to iOS 9, iOS 9 was released almost 4 years ago so iOS 8 is too old to support in App Center.
I hope you understand why we made this decision.
