### ISSUE TITLE
Make the API more Swifty

### ISSUE THREAD

**Issue by sindresorhus** [microsoft/appcenter-sdk-apple#1627]
The API could be more user-friendly for Swift users.

Some quick examples of what I would recommend:

```diff
-MSCrashes.hasCrashedInLastSession()
+MSCrashes.hasCrashedInLastSession
```

```diff
-MSCrashes.setDelegate(self)
+MSCrashes.delegate = self
```

```diff
-func crashes(_ crashes: MSCrashes!, willSend errorReport: MSErrorReport!) {
+func crashes(_ crashes: MSCrashes, willSend errorReport: MSErrorReport) {
```

```diff
-MSCrashes.disableMachExceptionHandler()
-MSAppCenter.start("{Your App Secret}", withServices: [MSCrashes.self])
+MSAppCenter.start("{Your App Secret}", withServices: [MSCrashes.self], options: [.withoutMachExceptionHandler])
```

```diff
-MSCrashes.setEnabled(false)
-MSCrashes.setEnabled(true)
-MSCrashes.isEnabled()
+MSCrashes.isEnabled = false
+MSCrashes.isEnabled = true
+MSCrashes.isEnabled
```

More here: https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/improving_objective-c_api_declarations_for_swift

**Comment by annakocheshkova** [comment]
@sindresorhus thanks for the suggestion. We are always open to the ways to improve the SDK.

**Comment by jaelim-ms** [comment]
@sindresorhus I appreciate your suggestion for Swift methods of App Center SDK.  Unfortunately, it is not in our immediate plan to support it. We will keep this thread open for developers to comment and vote, and keep you posted once we decide to work on it.

**Comment by tonyarnold** [comment]
@jaeklim none of @sindresorhus has suggested requires you to use Swift directly. 

This can all be done by properly structuring your Objective-C API using properties (both instance and class properties). I'll draw up a PR with at least what @sindresorhus has suggested above as an exemplar.

**Comment by Jamminroot** [comment]
@tonyarnold sure, feel free to create PR.

**Comment by iamclement** [comment]
Thanks for bumping up the topic and submitting a PR @tonyarnold . This is indeed some good improvements we can take, we are welcoming contributions. We’ll review the [PR](#1999 ). FYI among other thing we are looking at to approve a PR is the consistency between modules particularly because this topic impacts all modules. If any breaking change is to be added it should be added in a separate PR because it’ll probably stack up until the next SDK major version will show up. If we think we need to iterate on this we can create feature branches.

**Comment by AnastasiaKubova** [comment]
The feature has been released in [4.0.0](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.0.0) version of App Center.

**Comment by tonyarnold** [comment]
Please pass on my thanks to your team, @AnastasiaKubova 😁

**Comment by sindresorhus** [comment]
Really nice work on this everyone.

---

I did notice one thing though. It went from `MSAppCenter.isEnabled()` to `AppCenter.enabled`. This should be `AppCenter.isEnabled`.

**Comment by vvechkanov** [comment]
Hi @sindresorhus!
We are glad that you like our work! What about your note we were considering both options and decide to write it this way. [Here](https://github.com/microsoft/appcenter-sdk-apple/pull/2201#discussion_r510370154) you can found our PR, with discussion. The main idea was consistency between ObjC and Swift code. We use AppCenter.enabled as a name for property and `is_` and `set_` as prefixes for getters and setters.

**Comment by sindresorhus** [comment]
The whole point was to swiftify the API, meaning **less** consistency between Swift and Objective-C. Why not do it 100%?

**Comment by DmitriyKirakosyan** [comment]
@sindresorhus, we considered and discussed it thoroughly within the team while doing these changes, and it was decided to use `enabled` in Swift as this property is mutable.
Please feel free to open an issue or PR if you feel like it's not correct.

Due to other priorities we are currently not planning to do any updates related to Swift-friendly API.
