### ISSUE TITLE
iOS SDK missing setUserID

### ISSUE THREAD

**Issue by DerrickMilford** [microsoft/appcenter-sdk-apple#1955]
iOS SDK has no Functionality to set UserID for AppCenter Crashes. This functionality is present in the other AppCenter SDK like Android and work, yet the MSAppCenter Class, in the iOS AppCenter Framework, does not have that functionality.

**Comment by DerrickMilford** [comment]
Hi, I we have tested it on version 1.2 extensively and have not found the functionality available to us. 

We also found an issue, that for any project using Dynamic Frameworks instead of Static Libraries in their podfile, the only version available is 1.2. 
if I remove the "use_frameworks!" I can then update to 2.5 but then our app won't work because it requires Dynamic frameworks with other pods.

**Comment by guperrot** [comment]
1.12.0 was released after 1.2.0 so if you are still using 1.2.0 that's why the feature is missing for you.

We have always shipped our frameworks as static libraries (as binaries) so updating to 2.5.0 should have no impact if your app already worked with 1.2.0 as we never changed that. 1.2.0 is already using static libraries. One of our dev confirmed he could add "use_frameworks!" in an app using the latest SDK and it worked.

**Comment by Jamminroot** [comment]
Hey! 
We haven’t heard from you in a while, do you have any more questions? If so, please reopen the issue and let us know.  
Thanks for using App Center!
