### ISSUE TITLE
Crash when NSData object for SessionIdHistory in User Defaults is corrupt

### ISSUE THREAD

**Issue by Pegolon** [microsoft/appcenter-sdk-apple#2062]
We received a crash from a customer directly since the MSAppCenter SDK causes our app to crash during start. It looks like there is an NSData object stored in the User Defaults of our app. If this object cannot be deserialized the app crashes and cannot be used anymore.

https://github.com/microsoft/appcenter-sdk-apple/blob/455de8f0c8b53c8c82e3035562d6caccefa36762/AppCenter/AppCenter/Internals/Context/Session/MSSessionContext.m#L36

Stacktrace is like:
<img width="998" alt="Bildschirmfoto 2020-05-19 um 12 35 38" src="https://user-images.githubusercontent.com/34801/82316563-47319a80-99cd-11ea-9270-bb4d066bcecb.png">

Please make sure that this case does not make the host app completely unusable until the user goes to the Terminal and enters "defaults delete (our bundle identifier) SessionIdHistory".

Keep up the great work! Thanks.

**Comment by MatkovIvan** [comment]
Thanks for the report!

Could you please share raw crash report instead of screenshot? It can contain additional useful details.
You can get it from portal:
Select this crash -> "**Reports**" tab -> Select the device -> **Download** -> **Report as text**

![image](https://user-images.githubusercontent.com/1836384/82317598-30904100-99d7-11ea-86cc-0715cbe6e45f.png)

Also, specifying details like SDK version from issue template is still makes sense here to avoid assuming/guessing from our side.

> 1. Which SDK version are you using?
    e.g. 1.5.0
> 2. Which OS version did you experience the issue on?
    e.g. iOS 11

Anyway, I'm marking this one as "bug", we'll look what can we do with it.

Thank you

**Comment by Pegolon** [comment]
Unfortunately the app crashes without sending a report.

**Comment by MatkovIvan** [comment]
Ah. Plan B then 😄 :

Xcode -> Window -> **Devices and Simulators** -> **View Device Logs** -> Select this crash -> **Export Log**

**Comment by Pegolon** [comment]
It is a crash happening on a *customer* system und macOS. The linked code should be enough to fix a problem.

**Comment by MatkovIvan** [comment]
Ok, got it. Yeah, I just wanted to grab additional info that can be useful to investigate this crash.

> under macOS

Thanks for this detail.

**Comment by russelarms** [comment]
We've handled possible exceptions in NSKeyedUnarchiver in the recent release, so I'm closing this.
