### ISSUE TITLE
Getting appcenter signin  alert when application open using swift

### ISSUE THREAD

**Issue by arihant08** [microsoft/appcenter-sdk-apple#2121]
![IMG_3396](https://user-images.githubusercontent.com/44368018/86346471-96304800-bc7a-11ea-83c4-8a8da597698f.PNG)

SDK version - 3.3.0
iOS - 13
Swift - 5.0

Our application is open for public download (public page).

When application launch I am getting app signin alert, I don't need to show the alert for user.

**Comment by MatkovIvan** [comment]
Hi @arihant08 ,

App Center SDK doesn't show this alert by default (since 3.0.0). Please make sure that you do not set `MSDistribute.updateTrack` to private. You can find more details about this behaviour in this [doc](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/ios#use-private-distribution-group)

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
