### ISSUE TITLE
Support AppCenter/Distribute for Swift Package Manager

### ISSUE THREAD

**Issue by Petr-2019** [microsoft/appcenter-sdk-apple#2129]
I'm an engineer from Outlook iOS team. I'm trying to migrate the Hockey SDK to App Center SDK. I read the document and found that:

`Only the Analytics and Crashes modules support the use of Swift Package Manager at the moment.`

Is there any plan when this will be supported?

**Comment by MatkovIvan** [comment]
Distribute module has string resources that supported only in [Swift 5.3](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md). This swift version will be available only in Xcode 12, it's in beta now. So, it cannot be released for currently "last stable" tools.
See [original feature request](https://github.com/microsoft/appcenter/issues/1295#issuecomment-501502994) thread for details.

**Comment by Petr-2019** [comment]
Got it, I'll close this one

**Comment by Petr-2019** [comment]
@MatkovIvan 

Ah wait, so is it feasible only use AppCenter/Distribute for Cocoa/Carthage, and in the meantime integrate the `AppCenter/Analytics` and `AppCenter/Crashes` with Swift Package Manager?

**Comment by MatkovIvan** [comment]
🤔 

I guess you will get "core" duplicates because it will be included as sub dependency second time by CocoaPods. Carthage should work because you're linking frameworks manually there.

**Comment by Dids** [comment]
Since Xcode 12 is publicly out now, is there an ETA on when the Distribute module will be released?

**Comment by MatkovIvan** [comment]
@Dids no ETA yet

**Comment by StNebel** [comment]
@Petr-2019 plz reopen it

**Comment by aaronrogers** [comment]
It's a new month.  📆 

Any updates? 🤞

**Comment by MatkovIvan** [comment]
@aaronrogers It's already in our backlog, we'll pick it up soon

**Comment by lickel** [comment]
I just opened a PR with a working implementation.

**Comment by Jamminroot** [comment]
Thanks, @lickel, please let us some time to review and test it

**Comment by MatkovIvan** [comment]
Required changes have been merged to `develop` branch. It will be available in the next release

**Comment by lickel** [comment]
I left a comment on your [updated PR](https://github.com/microsoft/appcenter-sdk-apple/pull/2222#discussion_r526194138) explaining a minor issue with your updated implementation.

**Comment by AnastasiaKubova** [comment]
Hi @lickel ! Thanks for the reply! I checked your variant with `SWIFTPM_MODULE_BUNDLE` but during testing I had some problems.

Firstly, for correct work it, needed to rename the package name because during testing the app was crashed with an error like this:
` *** Terminating app due to uncaught exception 'SwiftPMResourcesAccessor', reason: 'unable to find bundle named App_Center_AppCenterDistribute'`

The second point, after renaming the package it still didn’t work because the `SWIFTPM_MODULE_BUNDLE` looks like already return a path to the bundle, but you tried to get from this path another bundle.

Besides, this way fits good for getting resources like images, files and etc., but I didn't find any clear guidelines how it should use with strings resources.

But anyway, I checked it with dynamic libraries and it works right for me, but I do not fully understand why you want to use the Distribute module in dynamic libraries? Our Distribute module supports in-app updates only for iOS apps.

**Comment by lickel** [comment]
When you process strings, you should basically return strings via `NSLocalizedStringFromTableInBundle(stringToken, @"AppCenterDistribute", SWIFTPM_MODULE_BUNDLE, @"")`

What I had originally done is copy the *entire* bundle as is into the module's bundle. If you use process, it'll move the strings directly into the bundle. 

With process, you can just do `bundle = SWIFTPM_MODULE_BUNDLE` and skip the secondary URL bit entirely. 

--

I don't personally want to use this in a dynamic library, I just mean your version could have issues in that context. 

The bigger issue is you're hard coding an internal implementation detail (the bundle name) rather than the macro. That bundle name could change in any update to SPM.

**Comment by AnastasiaKubova** [comment]
Ok, I got it. Thanks for mention it. We will prepare a separate PR with a fix for it.

**Comment by ConnorQi** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
