### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_MSACAppCenter"

### ISSUE THREAD

**Issue by johnborges** [microsoft/appcenter-sdk-apple#2269]
### **Description**

Unable to build barebones project making use of the `AppCenter` SDK. Getting `Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_MSACAppCenter"`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add 'AppCenter' to podfile
2. Run `pod install`
3. Add:
```swift
import AppCenter

AppCenter.configure(withAppSecret: "{Your App Secret}")
```
4. Build Project

### **Details**

1. Which SDK version are you using?
    - 4.1.0
2. Which OS version did you experience the issue on?
    - iOS 14.4 Simulator
3. Which Cocoapods version are you using (run `pod --version`)?
    - 1.10.1
4. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Simulator iPhone 12 mini
5. What language are you using?
    - Swift
6. What third party libraries are you using?
    - none 
7. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
   - AppCenter is not accessible.

**Comment by DmitriyKirakosyan** [comment]
Hi @johnborges 

Thank you for getting in touch with us.

I tried to reproduce the issue but it works for me as expected.

Try to clear the Xcode cache by running:
```rm -rf ~/Library/Developer/Xcode/DerivedData```

Also make sure the `$(inherited)` row added to the **Other Linker Flags** section of **Build Settings** for the target.

If it doesn't help, try to clean the cocoapods cache as well.

If nothing helps, could you please try to reproduce the issue on a new project?

**Comment by johnborges** [comment]
@DmitriyKirakosyan Thanks for the suggestions. I have tried everything you mentioned, but without success. The only thing that worked was manually adding the .xcframework file to the target of my project. This was after following the CocoaPods instructions.

**Comment by DmitriyKirakosyan** [comment]
@johnborges thank you for the update!

Could you confirm that the problem is resolved for you and I can close this issue?

Also, have you tried to deintegrate pods and reinstall it as described [here](https://stackoverflow.com/a/34765245/4098529)?
I'm suspecting that your pods linking was broken at some point and that is why you faced that error.
[Cocoapods troubleshooting guides](https://guides.cocoapods.org/using/troubleshooting.html) may be worth checking as well.

Sorry if I sound like a broken record, but It would be really great if you could try to reproduce it on a new empty Xcode project and provide a detailed repro steps to help investigating the issue further.

**Comment by johnborges** [comment]
Resolved for now. Thanks, Ill try that too.
