### ISSUE TITLE
Could appcenter sdk be changed to dynamic framework

### ISSUE THREAD

**Issue by yulin-li** [microsoft/appcenter-sdk-apple#2340]
**Is your feature request related to a problem? Please describe.**

I am building a dynamic framework depends on appcenter SDK, as appcenter SDK is a static framework, I need to static link it into my framework.

At this time, if an app uses both my framework and appcenter sdk, then the app will contains duplicated appcenter sdk binaries, one in the app, and another one in my framework. This causes building warnings and size increasing

**Describe the solution you'd like**

Change the appcenter sdk to a dynamic framework, then all other framework/app could share the same binary

**Describe alternatives you've considered**

**Additional context**

**Comment by yulin-li** [comment]
cc @purifier1990

**Comment by DmitriyKirakosyan** [comment]
Hi @yulin-li 

Thank you for getting in touch with us!

Unfortunately, we don't have any plans to support dynamic frameworks at this moment due to other priorities.
Also, having dynamic frameworks will cause issues in crash reporting for some cases. For example, there is a known issue with handling C++ crashes happening in a library linked dynamically, please check the post here: https://github.com/microsoft/appcenter-sdk-apple/issues/2042#issuecomment-620657538.

We already have such feature request here: https://github.com/microsoft/appcenter/issues/1642.
I'm closing this issue as a duplicate, please track the progress in the original issue.
