### ISSUE TITLE
Does not compile in Xcode 13

### ISSUE THREAD

**Issue by cbauer10** [microsoft/appcenter-sdk-apple#2399]
### **Description**

I am including the `AppCenter` SDK in an podspec.  The SDK fails in a testing target with:

> Undefined symbol: _OBJC_CLASS_$_MSACAnalytics
> Undefined symbol: _OBJC_CLASS_$_MSACCrashes
> Undefined symbol: _OBJC_CLASS_$_MSACAppCenter

This compiles properly on Xcode 12/Catalina, but fails on Xcode 13/Monterey

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Consume `AppCenter` SDK as a dependency to a podspec
2. Execute a test in Xcode 13 

### **Details**

1. Which SDK version are you using?
    - 4.4.1
2. Which OS version did you experience the issue on?
    - iOS 15
3. Which Xcode version did you build the app with?
    - Xcode 13.2.1
5. Which Cocoapods version are you using (run `pod --version`)?
    - 1.11.2
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 12 Pro physical device & iPhone 13 Pro emulator
7. What language are you using?
    - [ ] Objective C
    - [X] Swift
8. What third party libraries are you using?
    - NA
9. Please enable verbose logging for your app using `MSAppCenter.setLogLevel(.verbose)` before your call to `MSAppCenter.start(...)` for Swift, or `[MSAppCenter setLogLevel:MSLogLevelVerbose]` before `[MSAppCenter start: ...]` for Objective C and include the logs here:
    - Cannot get to this point as it doesn't even compile

**Comment by DmitriyKirakosyan** [comment]
Hi @cbauer10 , thank you for getting in touch with us!

I tried to reproduce the issue but with no luck. My versions: Monterey 12.1, Xcode 13.2.1, cocoapods 1.11.2, iOS 15.2.
Everything works as expected and project compiles for me.
Could you try to reproduce the issue on an empty project?

**Comment by cbauer10** [comment]
Of course.  Here is an example that I create very quickly that demonstrate the issue.  I only has a test in it that starts the tracking.  It will not compile the test target.

https://github.com/cbauer10/MyLibrary

**Comment by DmitriyKirakosyan** [comment]
@cbauer10 Thank you for your sample! It turned out that Cocoapods doesn't properly link dependencies of the main target (MyLibrary_Example) to its subtarget (MyLibrary_Tests). Here are related issues:
https://github.com/CocoaPods/CocoaPods/issues/7558
https://github.com/krzyzanowskim/OpenSSL/issues/54

For some reason the test project doesn't have the flags `-framework "AppCenter" -framework "AppCenterAnalytics" -framework "AppCenterCrashes"` in its config.

My `Example/Pods/Target Support Files/Pods-MyLibrary_Tests/Pods-MyLibrary_Tests.debug.xcconfig`:
```
OTHER_LDFLAGS = $(inherited) -l"c++" -l"sqlite3" -l"z" -framework "CoreTelephony" -framework "Foundation" -framework "SystemConfiguration" -framework "UIKit"
```
My `Example/Pods/Target Support Files/Pods-MyLibrary_Example/Pods-MyLibrary_Example.debug.xcconfig`:
```
OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"sqlite3" -l"z" -framework "AppCenter" -framework "AppCenterAnalytics" -framework "AppCenterCrashes" -framework "CoreTelephony" -framework "Foundation" -framework "MyLibrary" -framework "SystemConfiguration" -framework "UIKit"
```

If you add missing frameworks in `Pods-MyLibrary_Tests.debug.xcconfig` it starts compiling successfully.
You can also work it around by removing line `inherit! :search_paths` in your Podfile's test target.

I'm closing this issue as it is not related to the AppCenter SDK but feel free to reopen if you have additional points.
