### ISSUE TITLE
Is there an alternative to setCustomProperties?

### ISSUE THREAD

**Issue by st0ckh01mDev** [microsoft/appcenter-sdk-apple#2478]
**Is your feature request related to a problem? Please describe.**
Yes, my team using AppCenter iOS SDK 4.2.0 version and I started implementing one feature using `setCustomProperties(properties)` (where you can set `CustomProperties`) which I assumed that will be visible in the Crashes/Analytics for each of the crashes and analytics. Looking at the Crash in AppCenter, if we see those custom properties which are set ONLY once and will be visible in all the crashes can be really helpful.

I realized that in version 4.4.0 MSACCustomProperties classes are removed and no longer available, seems like no option for me right now to have this type of functionality.

**Describe the solution you'd like**
`AppCenter.start(withAppSecret: "ourAppSecretValue", services: [Analytics.self, Crashes.self])`

`// after this`

```
        let properties = CustomProperties()

        properties.set("value1", forKey: "key1")
        properties.set("value2", forKey: "key2")

        AppCenter.setCustomProperties(properties)
```

These two properties key1 and key2 will be only set once right after we start the SDK and will be submitted to AppCenter along with all the future Crashes data and can be seen in the Dashboard like you show the information of User Device, iOS version etc.

This way I can understand more about the crash and in how was the environment (different values) when this crash was happened.

**Describe alternatives you've considered**
I am looking for a solution which allow me to set different properties once I start `AppCenter SDK`. Those will be used by the SDK when there will be a new crash and it will be submitted along with the crash to the AppCenter and the same can be visible in the Dashboard.

**Additional context**
Then those keys and values can be display for all the crashes which occurred after we set these values, it also meaning that keys/values can be different based on various conditions and it has to consider this as well.
[
<img width="783" alt="Screenshot 2023-03-30 at 11 34 28" src="https://user-images.githubusercontent.com/129380469/228795075-acabb876-a95a-4cf1-9a93-fddda0ae1533.png">
](url)

This is the related ticket raised before https://github.com/microsoft/appcenter/issues/2110

**Comment by DmitriyKirakosyan** [comment]
Hi @st0ckh01mDev , thanks for reaching out!

`CustomProperties` were removed from API, but since they were not visible on the AppCenter portal, this API would not help you anyway.

To add properties to your crash log, you can use attachments API, see [Add attachments to a crash report](https://learn.microsoft.com/en-us/appcenter/sdk/crashes/ios#add-attachments-to-a-crash-report) doc.

For handled errors, there is an API for providing attachments and properties, see [Handled Errors](https://learn.microsoft.com/en-us/appcenter/sdk/crashes/ios#handled-errors) doc.

Hope it answers your question. I'm closing this issue, but feel free to comment if you still have concerns and I'll reply shortly.
